title: Giuseppe's 1hr Projects
description: A dad of 2 exploring microcontrollers, FPGAs, and edge AI — one hour at a time.
author: Giuseppe
email: giuseros85@gmail.com
url: https://giuseros.github.io

theme: minima

future: true

plugins:
  - jekyll-feed

markdown: kramdown
